debug: true
language: ruby
cache: bundler
rvm:
- 2.1.1
before_install:
- gem --version
before_script:
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bundle exec rake spec || false'
addons:
  code_climate:
    repo_token:
      secure: FboAfv2OSlPyh8NoftC/TbBP6b3N690+SZFblMK8Gq7PiqPIgFVT/DdlinhADqfPqt9KWnl/8XfxN8OwReYYJwDDDvVUhtb1LTadRc1c+W2VYThwQNIgS2yEvMl9E4hFTsVJE1teYo1Io2jlxiuQ8qU3Ld5P0eTiqjaH6z9N8LI=
env:
  global:
  - secure: moYIRlGTTW3q7BGf6zF2xZaRMwlhkG9esUg1ttxwlzovpZ1Y2Nyn5fUTNFr2aQEW6OBHKhws9AdMJ5qZjtfbHnW0gbghzRuWCsZZPrZhhrCCLYzMitFq1D+ag+mMwbQQi9WCn8sa6d7E9sK7CTrfxBrwhIbGvplQrTJdhW8M7GM=
    secure: UWYNVX2Tnf5RomNH7EicwbT0urynSmxo6CU7mqkiOTMl2sSTJrmsVRt4plL2nW/AKmhlZEaXZbkiEYEu+ouI3Vh5AjIFcKPgyPj8WDTXb9q4weduunHsOuoZ9Ghwspby2sjqqvnUiG1sxKF5krDGNOEXRR2u/FU6P1RMpY4zL+o=
  - secure: Yni8xDw/gFFOcs8owM9bT+Q6Sy0F8JzBE1lutMPqs/f8HrBd4EWZZT5AzgJv28WrghwjJExch6TgMRfbksLyn6+Tynp7CiEWPKgqCu0lHm+UVENU2StVg9TPjwmuFAuE/1S/6n62AnQ+N2iXW64fn48VLPs8BaRec/lgqB2R6JU=
  - secure: C+lPoXt8MN38fnuwvPA7kbdwnky42rCT7PcEu0/u+gWnmtrruXt6k2zQ+AZ/cZoPZKVHvwbZXQp3vxBsORyvgTtWR4pK9Jo3vVp2/ZZbm01zpa49GVVE6R8PZXnSAaHl2dBNWOgBMiw0seG31J3JflB9C7I7+qLX3RLV5VFZ1EI=
  - secure: VtU6hzw6Hk97lZPQuLXDmUQkUh5uaQHqzgmsFhSPe7XV1ZrudIAJG6kolUrkvdJgNzZaHKUzuVgCPK9pGI1SwlFS7Lsdlfl/Dj2hbGFsZ8WQfEZ5yiVYL2aA9K5Ru9hg61RbL+1U4UUwI2qQDYwdp6qoXndIpxwUg3qKSSAhOHQ=
  - secure: MfFoD9uFB9nq/bPc+JZbLh9nuRD9ESit376DYgW4Ls96kCVRA7IKrYu4F7kqIcFz8PRO/ljoT0BCZlu8veuD75AhpU0lY+eU0LkPQWjwHE7+kv3YjIHT+tm59mEDe8JVsIKapI4Lwm2vf1hmL9NfFuhAWw3cdVphkE9tUkigbv8=
